import { Josefin_Sans} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";
import NextThemeProvider from "@/components/NextThemeProvider";

const josefin = Josefin_Sans({
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"

      suppressHydrationWarning
      className={`${josefin.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-background text-foreground">
        <NextThemeProvider>
          <Navbar/>
        <main>
          {children}
        </main>
        <Footer/>
        </NextThemeProvider>
        <Toaster/>
        </body>
    </html>
  );
}
